broadlink:
  BLSH: /home/jie/life_codes/python-broadlink/cli/broadlink_cli.sh
  BCMD: /home/jie/life_codes/python-broadlink/cli/broadlink_cli
  em_files:
    em1: /home/jie/life_codes/python-broadlink/cli/file_em_em1
    em2: /home/jie/life_codes/python-broadlink/cli/file_em_em2
    em3: /home/jie/life_codes/python-broadlink/cli/file_em_em3
    em4: /home/jie/life_codes/python-broadlink/cli/file_em_em4
  signal_files:
    tv_power: /home/jie/life_codes/python-broadlink/cli/file_signal_tv_power
    tv_mute: /home/jie/life_codes/python-broadlink/cli/file_signal_tv_mute
    aircon_on: /home/jie/life_codes/python-broadlink/cli/file_signal_aircon_on
    aircon_off: /home/jie/life_codes/python-broadlink/cli/file_signal_aircon_off
webhooks:
  em:
    switch_aircon_livingroom: em1
    switch_aircon_bedroom: em2
    switch_aircon_kidsroom: em3
    switch_aircon_studyroom: em4
    pushbutton_tv_power: em2 
    pushbutton_tv_mute: em2
  sg:
    switch_aircon_livingroom_on: aircon_on
    switch_aircon_livingroom_off: aircon_off
    switch_aircon_bedroom_on: aircon_on
    switch_aircon_bedroom_off: aircon_off
    switch_aircon_kidsroom_on: aircon_on
    switch_aircon_kidsroom_off: aircon_off
    switch_aircon_studyroom_on: aircon_on
    switch_aircon_studyroom_off: aircon_off
    pushbutton_tv_power_push: tv_power
    pushbutton_tv_mute_push: tv_mute
telegram:
  url: "https://api.telegram.org/bot666111111:AAFHp3SQNqTyKycVcCegkR511111/sendMessage"
  chat_id: "6543011111"
